version: '3'
services:
    udagram-frontend:
        build: ./udagram-frontend
        container_name: udagram-frontend
        volumes:
            - ./udagram-frontend:/usr/src/app
        restart: always
        ports:
            - "8100:80"        
    udagram-feed:
        build: ./udagram-api-feed
        container_name: udagram-feed
        restart: always
        volumes:
            - $HOME/.aws:/root/.aws       
        environment:
            POSTGRES_USERNAME: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
            POSTGRES_DB: $POSTGRES_DB 
            POSTGRES_HOST: $POSTGRES_HOST
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_BUCKET: $AWS_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"                             
    udagram-user:
        build: ./udagram-api-user
        container_name: udagram-user
        restart: always
        environment:
            POSTGRES_USERNAME: $POSTGRES_USERNAME
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
            POSTGRES_DB: $POSTGRES_DB 
            POSTGRES_HOST: $POSTGRES_HOST
            AWS_REGION: $AWS_REGION 
            AWS_PROFILE: $AWS_PROFILE 
            AWS_BUCKET: $AWS_BUCKET
            JWT_SECRET: $JWT_SECRET
            URL: "http://localhost:8100"                
    reverseproxy:
        image: nginx:latest
        container_name: reverseproxy
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        ports:
            - 8080:8080
        depends_on:
            - udagram-user
            - udagram-feed     
        